### ISSUE TITLE
Can't run outside of the meinsum directory

### ISSUE THREAD

**Issue by jevandezande** [avcopan/meinsum#1]
I get the following error when I attempt to run it in a directory other than meinsum/ or try to import into the python (2 and 3) terminal outside of the local directory.

```
Traceback (most recent call last):
  File "<string>", line 28, in <module>
ImportError: No module named theory.ccd.ccd
```

Any ideas what is happening?

**Comment by avcopan** [comment]
Do you have path/to/meinsum in your PYTHONPATH?  For me, it looks like

export GITHUB=/home/avcopan/Documents/code/github
export PYTHONPATH=$GITHUB/meinsum/

**Comment by jevandezande** [comment]
I knew I was doing something dumb, apparently '~' is not expanded when inside quotes.
