### ISSUE TITLE
Reorganize directories

### ISSUE THREAD

**Issue by jevandezande** [avcopan/meinsum#2]
I think it would make more sense if you reorganized such that you aren't importing from lib, but that instead all of your code is imports from your module name, see [qgrep](https://github.com/jevandezande/qgrep) for how I organized my code. You could perhaps come up with a fancy name for this entire module (I feel as though meinsum is really more about a specific feature).

Here's how I would organize it. (ac_code is the stand-in for the new name, make sure it is unique)

ac_code/
- ac_code/
  - theory/
    - ccd.py
    - ccsd.py
  - blocks.py
  - compress.py
  - ...
- inputs/
  - ccd/
    - h2o.inp
  - ccsd/
    - h2o.inp
  - ...
- tests/
  - test code for each individual file (I realize this is probably a pipe dream)

Just a thought.

**Comment by avcopan** [comment]
Yeah, you're probably right about the directory organization -- I think
I'll go ahead and do that.  I think I'll keep the name though.  I may need
some help with the unit tests.

**Comment by avcopan** [comment]
Is there any way to make python skip directories?  I really hate having all
of the theory codes in one directory ...
